name: Generate Snake

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Create the `dist` directory to prevent the error
    - name: Create dist directory
      run: mkdir -p dist

    # Generates the snake (GIF)
    - uses: Platane/snk@v2
      id: snake-gif
      with:
        github_user_name: harshitjain1924

    # Check if snake files exist
    - name: List files in dist
      run: ls dist

    # Push the changes to the output branch
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: output
        force: true

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output
        build_dir: dist
        keep_history: false
        allow_empty_commit: true
        jekyll: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
