name: Generate Snake Gif
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake Gif
        uses: Platane/snk@v2
        with:
          github_user_name: harshitjain1924  # Your GitHub username

      - name: Upload Snake Gif
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: snake-gif
          path: ./snake.svg  # Ensure this is the correct path for the generated image
