name: Generate Snake Gif
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake Gif
        uses: Platane/snk@v2
        with:
          github_user_name: harshitjain1924  # Your GitHub username
          output: github-contribution-grid-snake.gif  # Ensure this is correct

      - name: Upload Snake Gif
        uses: actions/upload-artifact@v3  # Updated to the latest version
        with:
          name: snake-gif
          path: github-contribution-grid-snake.gif

