# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake
permissions: 
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2
      
      # Step 2: Create necessary directories
      - name: Create dist directory
        run: mkdir -p dist
      
      # Step 3: Generate the snake game from the GitHub contribution grid
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: harshitjain1924
          outputs: |
            dist/github-snake.svg
      
      # Step 4: Configure Git
      - name: Set up Git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      # Step 5: Pull latest changes to avoid conflicts
      - name: Pull latest changes
        run: git pull origin main

      # Step 6: Add and commit the changes
      - name: Commit files
        run: |
          git add dist/github-snake.svg
          git commit -m "Generated snake"

      # Step 7: Push changes to the main branch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
